# Generated by Django 6.0.1 on 2026-01-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_academicsession_classinfo_subject_term_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classes', to='core.subject'),
        ),
    ]
