# Generated by Django 6.0.1 on 2026-01-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_price', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('bank_name', models.CharField(default='First Bank', max_length=100)),
                ('account_number', models.CharField(default='1234567890', max_length=20)),
                ('account_name', models.CharField(default='NOCE DSSC', max_length=100)),
                ('term_duration_weeks', models.IntegerField(default=12)),
            ],
            options={
                'verbose_name': 'School Configuration',
                'verbose_name_plural': 'School Configurations',
            },
        ),
    ]
