# Generated by Django 6.0.1 on 2026-02-21 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studentprofile_date_of_birth_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='form_teacher',
            field=models.OneToOneField(blank=True, help_text='Teacher assigned as form teacher for this class', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_class', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g. OND, HND, B.Sc', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g. B.Ed, M.Sc', max_length=200),
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_info', models.ForeignKey(blank=True, help_text='Specific class for this assignment (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='core.classinfo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['teacher__last_name', 'subject__name'],
                'unique_together': {('teacher', 'subject', 'class_info')},
            },
        ),
    ]
