# Generated by Django 6.0.1 on 2026-04-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_replace_class_level_with_assigned_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='next_term_begins',
            field=models.DateField(blank=True, help_text='Date the next term begins', null=True),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='school_closes',
            field=models.DateField(blank=True, help_text='Date the school closes for the current term', null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='teacher_remark',
            field=models.CharField(blank=True, help_text='Optional free-text remark by the teacher', max_length=200),
        ),
    ]
