# Generated by Django 6.0.1 on 2026-04-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_schoolconfiguration_next_term_begins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='next_term_begins',
        ),
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='school_closes',
        ),
        migrations.AddField(
            model_name='term',
            name='next_term_begins',
            field=models.DateField(blank=True, help_text='Date the next term begins after this term', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='school_closes',
            field=models.DateField(blank=True, help_text='Date the school closes for this term', null=True),
        ),
    ]
